### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by sitenzo** [andrewdwallo/transmatic#12]
### Package Version

1.0.5

### PHP Version

8.1.6

### Laravel Version

10.38.1

### Which operating system do you use?

Windows

### Translation Service

AWS Translate

### Environment Details

Windows with PHP storm

### Problem Description

Documentation is out of date.

The documentation says :

`translate('Hello World', 'es');`

The functions says

`translate(string $text, array $replace = [], ?string $to = null)`

Second parameter needs to be array instead of string.

### Expected Behavior

Correct documentations

### Steps To Reproduce

Install and use 

`translate('Hello World', 'es');`

**Comment by andrewdwallo** [comment]
Sorry to just see this. Would you like to create a PR for this? If not I can do it, but was just offering.

**Comment by andrewdwallo** [comment]
Documentation updated in new release [v1.0.6](https://github.com/andrewdwallo/transmatic/tree/v1.0.6)
